hook.Add( "AddToolMenuCategories", "NpcDropCategory", function()
	spawnmenu.AddToolCategory( "Options", "NPC Drops", "#NPC Drops" )
end )

hook.Add( "PopulateToolMenu", "NpcAmmoDropSettings", function()
	spawnmenu.AddToolMenuOption( "Options", "NPC Drops", "ItsTheAmmoMenu", "NPC/Player Ammo Drops", "", "", function( panel )
	panel:ClearControls()
	panel:NumSlider( "Ammo Drop Chance", "ChanceOfAmmo", 0, 100, 0 )
	panel:Help( "Chance for NPCs to drop ammo" )
	panel:CheckBox( "NPC Ammo Drops", "NPCDropAmmo" )
	panel:Help( "Allow NPC ammo drops" )
	panel:CheckBox( "NPC Secondary Ammo Drops", "NPCDropAltAmmo" )
	panel:Help( "Allow NPCs to drop Secondary Ammo" )
	panel:CheckBox( "Disable NPC Weapon Drops", "DisableNPCWeaponDrop" )
	panel:Help( "Prevent NPC's from dropping weapons on death" )
	panel:CheckBox( "Player Ammo Drops", "PlayerDropAmmo" )
	panel:Help( "Allow Player ammo drops" )
	panel:CheckBox( "Player Secondary Ammo Drops", "PlayerDropAltAmmo" )
	panel:Help( "Allow Players to drop Secondary Ammo" )
end)
end)